load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "metal_shim",
    srcs = ["metal_impl.cpp"],
    hdrs = [
        "metal_hijack.h",
        "metal_shim.h",
    ],
    deps = [
        "//proto:metal_remote_cc_grpc",
        "//third_party/metal-cpp",
        "//third_party/metal-cpp:foundation-impl",
        "@grpc//:grpc++",
    ],
)
