syntax = "proto3";
package tnrc;

service TnrcService {
  rpc CreateSystemDefaultDeviceShim(CreateSystemDefaultDeviceShimRequest) returns (CreateSystemDefaultDeviceShimResponse);
  rpc CreateCommandQueueShim(CreateCommandQueueShimRequest) returns (CreateCommandQueueShimResponse);
  rpc ReleaseCommandQueueShim(ReleaseCommandQueueShimRequest) returns (ReleaseCommandQueueShimResponse);
  rpc CreateLibraryShim(CreateLibraryShimRequest) returns (CreateLibraryShimResponse);
  rpc ReleaseLibraryShim(ReleaseLibraryShimRequest) returns (ReleaseLibraryShimResponse);
  rpc CreateFunctionShim(CreateFunctionShimRequest) returns (CreateFunctionShimResponse);
  rpc ReleaseFunctionShim(ReleaseFunctionShimRequest) returns (ReleaseFunctionShimResponse);
  rpc CreateComputePipelineStateShim(CreateComputePipelineStateShimRequest) returns (CreateComputePipelineStateShimResponse);
  rpc ReleaseComputePipelineStateShim(ReleaseComputePipelineStateShimRequest) returns (ReleaseComputePipelineStateShimResponse);
  rpc CreateBufferShim(CreateBufferShimRequest) returns (CreateBufferShimResponse);
  rpc ReleaseBufferShim(ReleaseBufferShimRequest) returns (ReleaseBufferShimResponse);
  rpc CommitCommandBuffer(CommitCommandBufferRequest) returns (CommitCommandBufferResponse);
  rpc WaitUntilCompleted(WaitUntilCompletedRequest) returns (WaitUntilCompletedResponse);
}

message CreateSystemDefaultDeviceShimRequest {}

message CreateSystemDefaultDeviceShimResponse {
  uint32 device_id = 1;
  string device_name = 2;
}

message CreateCommandQueueShimRequest {
  uint32 device_id = 1;
}

message CreateCommandQueueShimResponse {
  uint32 command_queue_id = 1;
}

message ReleaseCommandQueueShimRequest {
  uint32 command_queue_id = 1;
}

message ReleaseCommandQueueShimResponse {}

message CreateLibraryShimRequest {
  uint32 device_id = 1;
  string source = 2;
  // TODO: Add options and error
}

message CreateLibraryShimResponse {
  uint32 library_id = 1;
}

message ReleaseLibraryShimRequest {
  uint32 library_id = 1;
}

message ReleaseLibraryShimResponse {}

message CreateFunctionShimRequest {
  uint32 library_id = 1;
  string function_name = 2;
  // TODO: Add options and error
}

message CreateFunctionShimResponse {
  uint32 function_id = 1;
}

message ReleaseFunctionShimRequest {
  uint32 function_id = 1;
}

message ReleaseFunctionShimResponse {}

message CreateComputePipelineStateShimRequest {
  uint32 device_id = 1;
  uint32 function_id = 2;
  // TODO: error
}

message CreateComputePipelineStateShimResponse {
  uint32 compute_pipeline_state_id = 1;
  sint64 max_total_threads_per_threadgroup = 2;
}

message ReleaseComputePipelineStateShimRequest {
  uint32 compute_pipeline_state_id = 1;
}

message ReleaseComputePipelineStateShimResponse {}

message MaxTotalThreadsPerThreadgroupShimRequest {
  uint32 compute_pipeline_state_id = 1;
}

message CreateBufferShimRequest {
  uint32 device_id = 1;
  uint64 length = 2;
  uint64 options = 3;
}

message CreateBufferShimResponse {
  uint32 buffer_id = 1;
}

message ReleaseBufferShimRequest {
  uint32 buffer_id = 1;
}

message ReleaseBufferShimResponse {}

message CommitCommandBufferRequest {
  uint32 command_queue_id = 1;
  uint32 compute_pipeline_state_id = 2;
  sint64 grid_size = 3;
  sint64 thread_group_size = 4;

  // buffer parameters
  repeated uint32 buffer_ids = 5 [packed = true];
  repeated uint32 buffer_offsets = 6 [packed = true];
  repeated uint32 index_map = 7 [packed = true];

  bytes all_buffer_data = 8;
}

message CommitCommandBufferResponse {
  uint32 command_buffer_id = 1;
}

message WaitUntilCompletedRequest {
  uint32 command_buffer_id = 1;
  repeated uint32 buffer_ids = 2 [packed = true];
}

message WaitUntilCompletedResponse {
  bytes all_buffer_data = 1;
}
