syntax = "proto3";
package tnrc;

service TnrcService {
  rpc CreateSystemDefaultDeviceShim(CreateSystemDefaultDeviceShimRequest) returns (CreateSystemDefaultDeviceShimResponse);
  rpc GetDeviceNameShim(GetDeviceNameShimRequest) returns (GetDeviceNameShimResponse);
  rpc CreateCommandQueueShim(CreateCommandQueueShimRequest) returns (CreateCommandQueueShimResponse);
}

message CreateSystemDefaultDeviceShimRequest {}

message CreateSystemDefaultDeviceShimResponse {
  uint32 device_id = 1;
}


message GetDeviceNameShimRequest{
  uint32 device_id = 1;
}

message GetDeviceNameShimResponse {
  string name = 1;
}

message CreateCommandQueueShimRequest{
  uint32 device_id = 1;
}

message CreateCommandQueueShimResponse {
  uint32 command_queue_id = 1;
}
